warning if snapshot too large
badock/ChameleonSnapshotting pull request #5
Opened 2018-03-28 15:04 UTC by zhenz

Changes include:
1. warn user if tar is larger than 8G and ask if continue
2. pull some properties into a separate properties file, instead of hard-coded

2018-03-28 15:04 UTC, zhenz commented
@priteau Please review! Thanks!

2018-03-29 01:56 UTC, zhenz commented
Sorry, @priteau , but can you hold on reviewing the code. I was trying to avoid copy-and-pastes in the code by creating a property file, but I might complicate things.  Will let you know when I'm done. Thanks!

2018-03-29 14:28 UTC, zhenz commented
@priteau Done fixing. I was trying to create a properties file for all properties, but to make it work I have to change CC-CentOS and CC-Ubuntu repos as well. So I gave that up and just modified the shell script. Please review! Thanks!

2018-03-29 17:39 UTC, priteau requested changes

2018-03-29 17:39 UTC, priteau commented on cc-snapshot
> +OPENSTACK_VENDER_DATA='http://169.254.169.254/openstack/latest/vendor_data.json'
s/VENDER/VENDOR

2018-03-29 17:39 UTC, priteau commented on cc-snapshot
> -# else #keystone v3 ...migrate to this at some point
Please keep the v3 code as we will likely move to it rather than keep using v2.0

2018-03-29 18:21 UTC, zhenz commented
@priteau Done fixing.

2018-04-02 15:25 UTC, priteau approved these changes

2018-04-02 15:25 UTC, merged